### ISSUE TITLE
Server crash when request only headers on well configured route

### ISSUE THREAD

**Issue by dsumac** [pmu-tech/stub-server#31]
## Context

We have correctly configure a route on server.

We can request the endpoint:

`curl  http://127.0.0.1:12345/endpoint/`

And the response is **correct**

## Problem

But when we request **only the headers**, the server crash:

`curl -I http://127.0.0.1:12345/endpoint/`

```
stub-server is running at http://127.0.0.1:12345
.../node_modules/@pmu-tech/stub-server/dist/cjs/stubServer.js:70
        name = typeof stub.response === 'function' ? stub.response(req) : stub.response;
                           ^

TypeError: Cannot read property 'response' of undefined
    at parseConfig (/node_modules/@pmu-tech/stub-server/dist/cjs/stubServer.js:70:28)
    at processStubRequest (/node_modules/@pmu-tech/stub-server/dist/cjs/stubServer.js:81:28)
    at .../node_modules/@pmu-tech/stub-server/dist/cjs/stubServer.js:130:74
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:281:22
    at param (/node_modules/express/lib/router/index.js:354:14)
    at param (/node_modules/express/lib/router/index.js:365:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /.nvm/versions/node/v16.6.2/bin/node
Arguments: /usr/local/Cellar/yarn/1.22.0/libexec/lib/cli.js start
Directory: /packages/stubs
Output:
```

Reason is probably the response is empty.

## More info

curl **-I** option fetch only headers

```
 -I, --head
              (HTTP FTP FILE) Fetch the headers only! HTTP-servers feature the command HEAD which this  uses  to
              get nothing but the header of a document. When used on an FTP or FILE file, curl displays the file
              size and last modification time only.

```

**Comment by tkrotoff** [comment]
`curl -I` performs a HEAD request. I guess you didn't specified a HEAD route inside your stubs/config.ts hence the crash.

However the crash is not clean, check PR https://github.com/pmu-tech/stub-server/pull/32
Now it will throw *"No route for 'HEAD' HTTP request method"*

Other related subject: if you specify HEAD as a route inside stubs/config.ts, TypeScript will complain. If there is a good use case for having a HEAD route, I will add it to the typings. Same for CONNECT, OPTIONS and TRACE. Officially supported methods are GET, POST, PUT, PATCH and DELETE.

**Comment by dsumac** [comment]
Yes I have not specify a head route.

But, as a user of a server, when a route exists, if I send a head request, I expect to get a response.
And that without declaring it.

Here, when a route exists (whatever the verb which is declared), I think we should automatically respond for a head request.
