### ISSUE TITLE
Make bin/stub-server port and config path configurable

### ISSUE THREAD

**Issue by tkrotoff** [pmu-tech/stub-server#4]
- Config path is hardcoded: https://github.com/pmu-tech/stub-server/blob/v0.2.0/bin/stub-server.js#L21
- Port number is hardcoded: https://github.com/pmu-tech/stub-server/blob/v0.2.0/bin/stub-server.js#L23

Use something like yargs or commander to parse command line arguments

**Comment by gko** [comment]
`-c` / `--config` for config file `-p` / `--port` for port ?
